image: ruby:2.3.0
before_script:
  - gem install bundler --no-ri --no-rdoc
  - mkdir -p /vendor/bundle
  - ls -lAh /vendor/bundle
  - bundle check --path=/vendor/bundle || bundle install --path /vendor/bundle --without=production,development,deploy,doc
test:
  script:
    - bundle exec rake test
rubocop:
  script:
    - bundle exec rubocop --rails --fail-level=warning
