image: ruby:2.3.0
before_script:
  - gem install bundler --no-ri --no-rdoc
  - mkdir -p /cache/bundle
  - ls -lAh /cache/bundle
  - bundle check --path=/cache/bundle || bundle install --path /cache/bundle --without=production,development,deploy,doc
  - bundle exec rake db:migrate RAILS_ENV=test
test:
  script:
    - bundle exec rake test
rubocop:
  script:
    - bundle exec rubocop --rails --fail-level=warning
